Todo_List/urls.py
from django.urls import path
from . import views

app_name = 'Todo_List'

urlpatterns = [
    path('', views.index, name='index'),
    path('download_all/', views.download_all_json, name="download_all"),
    path('logout/', views.user_logout, name="logout"),
    path('signup/', views.MyRegisterFormView.as_view(), name="signup"),
    path('login/', views.LoginFormView.as_view(), name="login"),

    path('<int:sheet_id>/<int:note_id>/change_status/', views.change_status, name='change_status'),
    path('<int:sheet_id>/<int:note_id>/note_delete/', views.note_delete, name='note_delete'),
    path('<int:sheet_id>/<int:note_id>/note_edit/', views.note_edit, name='note_edit'),
    path('<int:sheet_id>/sheet_delete/', views.sheet_delete, name='sheet_delete'),
    path('<int:sheet_id>/sheet_edit/', views.sheet_edit, name='sheet_edit'),
    path('create_sheet/', views.create_sheet, name='create_sheet'),
    path('<int:sheet_id>/', views.detail, name='detail'),
    path('<int:sheet_id>/create_note/', views.create_note, name='create_note'),

    path('<int:sheet_id>/<int:note_id>/copy_note/', views.copy_note, name='copy_note'),
    path('<int:sheet_id>/paste_note/', views.paste_note, name='paste_note'),

    path('<int:sheet_id>/download_json/', views.download_json, name='download_json'),

]

_MYfirst/urls.py
from django.contrib import admin
from django.urls import path, include
from Todo_List import views

urlpatterns = [
    path('', views.show_main, name='show_main'),
    path('Todolist/', include('Todo_List.urls')),
    path('admin/', admin.site.urls),

]

Todo_List/models.py
from django.db import models
from django.contrib.auth.models import User


class Sheet(models.Model):
    sheet_title = models.CharField('Main Title', default='Sheet_Title', max_length=20, help_text="M_Title")
    color = models.CharField('Color', default='Sheet_Color', max_length=25, help_text="Color Sheet")
    pub_date = models.DateField('Pub date')
    user_sheet = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):

        return self.sheet_title


class Note(models.Model):
    note_title = models.CharField('Note Title', default='Note_Title', max_length=20, help_text="Title")

    task_text = models.CharField('Note Task Text', default='Task Text', max_length=3000, help_text="Task")
    real_date = models.DateField('Real date')
    dead_line = models.DateField('Dead Line')
    status = models.CharField('status', default='Not Performed', max_length=20, help_text="N_Status")

    main = models.ForeignKey(Sheet, on_delete=models.CASCADE)

    def __str__(self):
        return self.note_title


class Note_buffer(models.Model):
    buf_title = models.CharField('Buffer Title', default='Buffer_Title', max_length=20, help_text="Buf_Title")
    buf_task = models.CharField('Buffer Task Text', default='Buffer_Task_Text', max_length=3000, help_text="Buffer Task")
    buf_real_date = models.DateField('Real date')
    buf_d_line = models.DateField('Dead Line')
    buf_status = models.CharField('status', default='Not Performed', max_length=20, help_text="N_Status")

    def __str__(self):
        return 'Buffer'

Todo_List/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=250, help_text='Username:')
    username = forms.EmailField(max_length=250, help_text='Email:')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'password1', 'password2',)


class LoginForm(AuthenticationForm):
    username = forms.EmailField(max_length=250, help_text='Email:')

    class Meta:
        model = User
        fields = ('username', 'password',)


class ColorCheckForm(forms.Form):
    hex_color = forms.CharField(max_length=25)

    def clean_hex_color(self):
        color = str(self.cleaned_data['hex_color'])
        if len(color) < 7 or len(color) > 7:
            raise ValidationError('Invalid value')
        if color[0] != '#':
            raise ValidationError('Invalid value')
        for element in color:
            if not element in "#ABCDEFabcdef1234567890":
                raise ValidationError('Invalid value')

        return color

Todo_List/views.py
from django.http import Http404, HttpResponseRedirect
from django.contrib.auth.models import User
from .models import Sheet, Note_buffer
from django.urls import reverse
from django.utils import timezone
from django.views.generic.edit import FormView
from .forms import SignUpForm, LoginForm, ColorCheckForm
from django.contrib.auth import login, logout
from django.shortcuts import render
from Todo_List.to_json import Note_Serializer
import zipfile, json, os, mimetypes, glob
from django.http import StreamingHttpResponse
from wsgiref.util import FileWrapper


def show_main(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('Todo_List:index', ))
    else:
        return render(request, 'Todo_List/main.html', )


def index(request):
    if request.user.is_authenticated:
        if request.user.is_staff:
            sheet_list = Sheet.objects.all()
            return render(request, 'Todo_List/Page_main.html', {'sheet_list': sheet_list})
        else:
            sheet_list = Sheet.objects.filter(user_sheet=request.user)
            return render(request, 'Todo_List/Page_main.html', {'sheet_list': sheet_list})
    else:
        return HttpResponseRedirect(reverse('Todo_List:login', ))


def detail(request, sheet_id):
    if Sheet.objects.get(id=sheet_id).user_sheet == request.user or request.user.is_staff:
        try:
            sheet = Sheet.objects.get(id=sheet_id)
        except:
            raise Http404("Листа нет :( Программист не виноват в код пробрались враги!")

        all_note_list = sheet.note_set.all()
        for note in all_note_list:
            note.real_date = timezone.now()

        return render(request, 'Todo_List/detail.html', {'sheet': sheet, 'all_note_list': all_note_list})
    else:
        raise Http404("Это не твой лист!!! (N_N) Я звоню в полицию!!!")


def create_note(request, sheet_id):
    if Sheet.objects.get(id=sheet_id).user_sheet == request.user or request.user.is_staff:
        try:
            sheet = Sheet.objects.get(id=sheet_id)
        except:
            raise Http404("Листа нет :( Программист не виноват в код пробрались враги!")

        sheet.note_set.create(note_title=request.POST.get('title', False), task_text=request.POST.get('task', False),
                              real_date=timezone.now(), dead_line=request.POST.get('dl', False))

        return HttpResponseRedirect(reverse('Todo_List:detail', args=(sheet.id,)))
    else:
        raise Http404("Это не твой лист!!! (N_N) Я звоню в полицию!!!")


def create_sheet(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = ColorCheckForm(request.POST)
            sheet = Sheet(sheet_title=request.POST.get('name_', False), pub_date=timezone.now())
            sheet.user_sheet = User.objects.get(pk=request.user.pk)

            if form.is_valid():
                sheet.color = form.cleaned_data['hex_color']
                sheet.save()

            return HttpResponseRedirect(reverse('Todo_List:index', ))
    else:
        return HttpResponseRedirect(reverse('Todo_List:login', ))


def sheet_delete(request, sheet_id):
    if Sheet.objects.get(id=sheet_id).user_sheet == request.user or request.user.is_staff:
        sheet = Sheet.objects.get(id=sheet_id)
        sheet.delete()
        return HttpResponseRedirect(reverse('Todo_List:index', ))
    else:
        raise Http404("Это не твой лист!!! (N_N) Я звоню в полицию!!!")


def note_delete(request, sheet_id, note_id):
    if Sheet.objects.get(id=sheet_id).user_sheet == request.user or request.user.is_staff:
        sheet = Sheet.objects.get(id=sheet_id)
        note = sheet.note_set.get(id=note_id)
        note.delete()
        return HttpResponseRedirect(reverse('Todo_List:detail', args=(sheet.id,)))
    else:
        raise Http404("Это не твой лист!!! (N_N) Я звоню в полицию!!!")


def change_status(request, sheet_id, note_id):
    if Sheet.objects.get(id=sheet_id).user_sheet == request.user or request.user.is_staff:
        sheet = Sheet.objects.get(id=sheet_id)
        note = sheet.note_set.get(id=note_id)
        if note.status == 'Not Performed':
            note.status = 'In progress'
        elif note.status == 'In progress':
            note.status = 'Performed'
        else:
            note.status = 'Not Performed'

        note.save()

        return HttpResponseRedirect(reverse('Todo_List:detail', args=(sheet.id,)))
    else:
        raise Http404("Это не твой лист!!! (N_N) Я звоню в полицию!!!")


def note_edit(request, sheet_id, note_id):
    if Sheet.objects.get(id=sheet_id).user_sheet == request.user or request.user.is_staff:
        try:
            sheet = Sheet.objects.get(id=sheet_id)
            note = sheet.note_set.get(id=note_id)
            if request.method == "POST":

                note.note_title = request.POST.get('title')
                note.task_text = request.POST.get('task')
                note.real_date = timezone.now()
                note.save()
                return HttpResponseRedirect(reverse('Todo_List:detail', args=(sheet.id,)))
            else:
                return render(request, 'Todo_List/note_edit.html', {'sheet': sheet, 'note': note})
        except Sheet.DoesNotExist:
            raise Http404("Note not found")
    else:
        raise Http404("Это не твой лист!!! (N_N) Я звоню в полицию!!!")


def sheet_edit(request, sheet_id):
    if Sheet.objects.get(id=sheet_id).user_sheet == request.user or request.user.is_staff:
        try:
            sheet = Sheet.objects.get(id=sheet_id)

            if request.method == "POST":
                form = ColorCheckForm(request.POST)
                sheet.sheet_title = request.POST.get('name_')
                sheet.pub_date = timezone.now()
                if form.is_valid():
                    sheet.color = form.cleaned_data['hex_color']
                    sheet.save()

                return HttpResponseRedirect(reverse('Todo_List:detail', args=(sheet.id,)))
            else:
                return render(request, 'Todo_List/sheet_edit.html', {'sheet': sheet})
        except Sheet.DoesNotExist:
            raise Http404("<h2>Note not found</h2>")
    else:
        raise Http404("Это не твой лист!!! (N_N) Я звоню в полицию!!!")


class MyRegisterFormView(FormView):
    form_class = SignUpForm

    success_url = "/Todolist/login/"

    template_name = "registration/signup.html"

    def form_valid(self, form):
        form.save()
        
        return super(MyRegisterFormView, self).form_valid(form)

    def form_invalid(self, form):
        return super(MyRegisterFormView, self).form_invalid(form)


class LoginFormView(FormView):
    form_class = LoginForm

    template_name = "registration/login.html"

    success_url = "/Todolist/"

    def form_valid(self, form):
        self.user = form.get_user()

        login(self.request, self.user)
        return super(LoginFormView, self).form_valid(form)


def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('Todo_List:login', ))


def copy_note(request, sheet_id, note_id):
    if Sheet.objects.get(id=sheet_id).user_sheet == request.user or request.user.is_staff:
        sheet = Sheet.objects.get(id=sheet_id)
        note = sheet.note_set.get(id=note_id)
        if not Note_buffer.objects.filter(id=1).exists():
            buffer = Note_buffer(buf_title=note.note_title, buf_task=note.task_text,
                                 buf_d_line=note.dead_line, buf_real_date=timezone.now(),
                                 buf_status=note.status)
            buffer.save()
            return HttpResponseRedirect(reverse('Todo_List:detail', args=(sheet.id,)))
        else:
            buffer = Note_buffer.objects.get(id=1)
            buffer.buf_title = note.note_title
            buffer.buf_task = note.task_text
            buffer.buf_d_line = note.dead_line
            buffer.buf_real_date = timezone.now()
            buffer.buf_status = note.status
            buffer.save()
            return HttpResponseRedirect(reverse('Todo_List:detail', args=(sheet.id,)))
    else:
        raise Http404("Это не твой лист!!! (N_N) Я звоню в полицию!!!")


def paste_note(request, sheet_id):
    if Sheet.objects.get(id=sheet_id).user_sheet == request.user or request.user.is_staff:
        try:
            sheet = Sheet.objects.get(id=sheet_id)
            buffer = Note_buffer.objects.get(id=1)
            sheet.note_set.create(note_title=buffer.buf_title, task_text=buffer.buf_task,
                                  real_date=timezone.now(), dead_line=buffer.buf_d_line,
                                  status=buffer.buf_status)

            return HttpResponseRedirect(reverse('Todo_List:detail', args=(sheet.id,)))
        except Note_buffer.DoesNotExist:
            raise Http404("<h2>Buffer is empty</h2>")
    else:
        raise Http404("Это не твой лист!!! (N_N) Я звоню в полицию!!!")


def download_json(request, sheet_id):
    if Sheet.objects.get(id=sheet_id).user_sheet == request.user or request.user.is_staff:
        sheet = Sheet.objects.get(id=sheet_id)
        note_list = sheet.note_set.all()
        file_name = str(sheet.sheet_title) + '.json'
        path = os.path.join(os.path.abspath(os.path.dirname(__file__)))

        path += '\\files\\'
        files_ = glob.glob(path + '/**/*.json', recursive=True)

        for f in files_:
            try:
                os.remove(f)
            except OSError as e:
                print("Error: %s : %s" % (f, e.strerror))

        path += file_name
        open(path, 'w')
        f = open(path, 'a')

        for note in note_list:
            dict_note = Note_Serializer(note)
            json.dump(dict_note.data, f)

        f.close()

        file_name = os.path.basename(path)
        chunk_size = 8192
        response = StreamingHttpResponse(FileWrapper(open(path, 'rb'), chunk_size),
                                         content_type=mimetypes.guess_type(path)[0])

_MYfirst/templates/Todo_List/Page_main.html
{% extends 'base.html' %}

{% block titel%}To Do List{% endblock %}

{% block link_css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/page_main.css' %}">
{% endblock %}

{% block content %}


{% if user.is_staff  %}

    {% if sheet_list %}
        <div class="sheet_list">
                {% for sheet in sheet_list %}
                <div>
                    <a href="{% url 'Todo_List:detail' sheet.id %}">{{ sheet.sheet_title }}</a>
                    <p>Owner: {{ sheet.user_sheet.first_name }} </p><br>
                </div>

                {% endfor %}
        </div>
            <div class="add_sheet_form">
                <hr>
                <h2>Add Sheet:</h2>
                <form action="{% url 'Todo_List:create_sheet'  %}" method="POST">
                {% csrf_token %}
                <input name="name_" type="text" required placeholder="Sheet Title..." ><br>
                    <input name="hex_color" type="text" required placeholder="Set hex color, like this - #FFFFFF" ><br>
                <button type="submit">Create Sheet</button>
                </form>
            </div>
        {% else %}
            <h2 class="empty_title">Empty:(</h2>
            <div class="add_sheet_form">
                <hr>
                <h2>Add Sheet:</h2>
                <form action="{% url 'Todo_List:create_sheet'  %}" method="POST">
                {% csrf_token %}
                <input name="name_" type="text" required placeholder="Sheet Title..." ><br>
                    <input name="hex_color" type="text" required placeholder="Set hex color, like this - #FFFFFF" ><br>
                <button type="submit">Create Sheet</button>
                </form>
            </div>
        {% endif %}
{% else %}
        {% if sheet_list %}
            <div class="sheet_list">
                {% for a in sheet_list %}
                    <div>
                        <a href="{% url 'Todo_List:detail' a.id %}">{{ a.sheet_title }}</a>
                    </div>
                {% endfor %}
            </div>
            <div class="add_sheet_form">
                <hr>
                <h2>Add Sheet:</h2>
                <form action="{% url 'Todo_List:create_sheet'  %}" method="POST">
                {% csrf_token %}
                <input name="name_" type="text" required placeholder="Sheet Title..." ><br>
                    <input name="hex_color" type="text" required placeholder="Set hex color, like this - #FFFFFF" ><br>
                <button type="submit">Create Sheet</button>
                </form>
            </div>
        {% else %}
            <h2 class="empty_title">Empty:(</h2>
            <div class="add_sheet_form">
                <hr>
                <h2>Add Sheet:</h2>
                <form action="{% url 'Todo_List:create_sheet'  %}" method="POST">
                {% csrf_token %}
                <input name="name_" type="text" required placeholder="Sheet Title..." ><br>
                    <input name="hex_color" type="text" required placeholder="Set hex color, like this - #FFFFFF" ><br>
                <button type="submit">Create Sheet</button>
                </form>
            </div>
        {% endif %}
    {% endif %}
{% endblock %}

_MYfirst/templates/Todo_List/detail.html
{% extends 'base.html' %}

{% block titel%} {{ sheet.sheet_title }} {% endblock %}

{% block link_css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/detail.css' %}">
{% endblock %}
{% block body_color %}
    <body style="background: {{ sheet.color }}">
    {% if user.is_authenticated %}

            {% block header %}
                <header class="header">

                    <div class="header_1">

                        <div class="user_name">
                            <p>User: {{ user.get_full_name }}</p>
                        </div>

                        <div class="logout">
                            <a href="{% url 'Todo_List:logout'%}">Log Out</a>
                        </div>

                        <div class = "download_all">
                            <a href="{% url 'Todo_List:download_all'  %}" >Download All Sheet</a>
                        </div>
                    </div>
                    <div class="header_2">
                        <a href="{% url 'Todo_List:index'  %}"> <div class="logo"></div></a>
                        <div class ="sheet_delete"><a href="{% url 'Todo_List:sheet_delete' sheet.id %}">Delete this Shit</a></div>
                        <div class="sheet_edit"><a href="{% url 'Todo_List:sheet_edit' sheet.id %}">Edit this Shit</a></div>
                        <div class="paste_note"><a href="{% url 'Todo_List:paste_note' sheet.id %}">Paste Note</a></div>
                        <div class="download"><a href="{% url 'Todo_List:download_json' sheet.id %}">Download Sheet</a></div>

                    </div>
                </header>
            {% endblock %}
        {% endif %}
    {% block content %}
        <h2> {{ sheet.sheet_title }} </h2>
        <em> {{ sheet.pub_date }}</em>

            {% if all_note_list %}
                <div class="note_list">

                    {% for note in all_note_list %}
                        <div>
                            <h2>{{ note.note_title }}</h2>
                            <p>{{ note.task_text }}</p>
                            <p><span>Dead Line:</span> {{ note.dead_line }}</p>
                            <p><span>Real Date:</span>{{ note.real_date}}</p>
                            <p><span>Status:</span>{{ note.status }}</p>
                            <hr>
                               <div class="change"><a href="{% url 'Todo_List:change_status' sheet.id note.id %}">Change Status</a></div>

                            <div class="delete_note"><a href="{% url 'Todo_List:note_delete' sheet.id note.id %}">Delete this Shit</a></div>
                            <div><a href="{% url 'Todo_List:note_edit' sheet.id note.id %}">Edit this Shit</a><br></div>
                            <div class="copy"><a href="{% url 'Todo_List:copy_note' sheet.id note.id %}">Copy</a></div>
                        </div>

                    {% endfor %}

                </div>
            {% else %}
                Заданий нет! Чилим мужики))))
            {% endif %}

        <div class = "note_form">
            <hr>
            <h2>Add Note:</h2>
                <form action="{% url 'Todo_List:create_note' sheet.id %}" method="POST">

                    {% csrf_token %}
                    <input class="title_field" name="title" type="text" required placeholder="Title..." ><br>

                    <textarea class="task_field" name="task" type="text" required placeholder="Task..." ></textarea><br>

                    <span>Dead Line:</span>
                    <input class="date_field" name="dl" type="date" required  ><br>

                    <button type="submit">Create Note</button>

                </form>

        </div>



    {% endblock %}
</body>
{% endblock %}

_MYfirst/templates/Todo_List/main.html
{% extends 'base.html' %}

{% block titel%}To Do List{% endblock %}

{% block link_css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
{% endblock %}

{% block content %}
    <div class = "main_block">
        <div class="login" >
            <a  href="{% url 'Todo_List:login' %}">Log In</a><br>
        </div>
        <div class="signup" >
            <a  href="{% url 'Todo_List:signup' %}">Sign Up</a>
        </div>
    </div>
{% endblock %}

_MYfirst/templates/Todo_List/note_edit.html
{% extends 'base.html' %}

{% block titel%}To Do List{% endblock %}
{% block link_css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/detail.css' %}">
{% endblock %}
{% block content %}
    <div class = "note_form">

        <h2>Edit Note:</h2>
            <form action="{% url 'Todo_List:create_note' sheet.id %}" method="POST">

                {% csrf_token %}
                <input class="title_field" name="title" type="text"  value="{{ note.note_title }}" ><br>

                <input class="task_field" name="task" type="text"  value="{{ note.task_text }}" ><br>

                <span>Dead Line:</span>
                <input class="date_field" name="dl" type="date" ><br>

                <button type="submit">Save</button>

            </form>
    </div>
{% endblock %}

_MYfirst/templates/Todo_List/sheet_edit.html
{% extends 'base.html' %}

{% block titel%}To Do List{% endblock %}
{% block link_css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/page_main.css' %}">
{% endblock %}
{% block content %}
<div class="add_sheet_form">
    <h2>Edit:</h2>
    <form action="{% url 'Todo_List:sheet_edit' sheet.id %}" method="POST">
        {% csrf_token %}
        <input name="name_" type="text" value="{{ sheet.sheet_title }}" placeholder="Sheet Title..." ><br>
        <input name="hex_color" type="text" value="{{ sheet.color }}" placeholder="Set hex color, like this - #FFFFFF" ><br>
        <button type="submit">Save</button>
    </form>
</div>
{% endblock %}