Todo_List/urls.py
from django.urls import path
from . import views

app_name = 'Todo_List'

urlpatterns = [
    path('', views.index, name='index'),
    path('download_all/', views.download_all_json, name="download_all"),
    path('logout/', views.user_logout, name="logout"),
    path('signup/', views.MyRegisterFormView.as_view(), name="signup"),
    path('login/', views.LoginFormView.as_view(), name="login"),

    path('<int:sheet_id>/<int:note_id>/change_status/', views.change_status, name='change_status'),
    path('<int:sheet_id>/<int:note_id>/note_delete/', views.note_delete, name='note_delete'),
    path('<int:sheet_id>/<int:note_id>/note_edit/', views.note_edit, name='note_edit'),
    path('<int:sheet_id>/sheet_delete/', views.sheet_delete, name='sheet_delete'),
    path('<int:sheet_id>/sheet_edit/', views.sheet_edit, name='sheet_edit'),
    path('create_sheet/', views.create_sheet, name='create_sheet'),
    path('<int:sheet_id>/', views.detail, name='detail'),
    path('<int:sheet_id>/create_note/', views.create_note, name='create_note'),

    path('<int:sheet_id>/<int:note_id>/copy_note/', views.copy_note, name='copy_note'),
    path('<int:sheet_id>/paste_note/', views.paste_note, name='paste_note'),

    path('<int:sheet_id>/download_json/', views.download_json, name='download_json'),

]

_MYfirst/urls.py
from django.contrib import admin
from django.urls import path, include
from Todo_List import views

urlpatterns = [
    path('', views.show_main, name='show_main'),
    path('Todolist/', include('Todo_List.urls')),
    path('admin/', admin.site.urls),

]

_MYfirst/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block titel%} Titel blyt {% endblock %}</title>
{% block link_css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
{% endblock %}
</head>
{% block body_color %}
    <body>
        {% if user.is_authenticated %}
            {% block header %}
                <header class="header">

                    <div class="header_1">

                        <div class="user_name">
                            <p>User: {{ user.get_full_name }}</p>
                        </div>
                        <div class="logout">
                            <a href="{% url 'Todo_List:logout'%}">Log Out</a>
                        </div>
                        <div class = "download_all">
                            <a href="{% url 'Todo_List:download_all'  %}" >Download All Sheet</a>
                        </div>
                    </div>
                    <div class="header_2">
                       <a href="{% url 'Todo_List:index'  %}"> <div class="logo"></div></a>
                    </div>
                </header>
            {% endblock %}
        {% endif %}
        {% block content%} Content blyt {% endblock %}
    </body>
{% endblock %}
</html>